name: parse_mode_setter
description: A plugin for Televerse. Let's you set parse mode all methods in one line.
version: 1.2.0
repository: https://github.com/xooniverse/ParseModeSetter
issue_tracker: https://github.com/xooniverse/ParseModeSetter/issues
funding:
  - https://buymeacoffee.com/heysreelal
topics:
  - televerse
  - telegram-bot
  - plugin
  - telegram

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  televerse: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
