name: parse_mode_setter
description: A plugin for Televerse. Let's you set parse mode all methods in one line.
version: 1.0.0
repository: https://github.com/xooniverse/ParseModeSetter
issue_tracker: https://github.com/xooniverse/ParseModeSetter/issues
funding:
  - https://buymeacoffee.com/heysreelal
topics:
  - televerse
  - telegram-bot
  - plugin
  - telegram

environment:
  sdk: ^3.4.4

dependencies:
  televerse: ^1.19.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
